import { Theme } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import { Permanent_Marker } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

const pm = Permanent_Marker({
  weight: '400',
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-en-permanent-marker',
})

const kgPrimaryDots = localFont({
  src: './fonts/KGPrimaryDots.ttf',
  variable: '--font-en-zt-kg-primary-dots',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kgPrimaryDots.variable} ${pm.className}  antialiased`}
      >
        <Theme>{children}</Theme>
      </body>
    </html>
  )
}
